const assert = require("node:assert/strict")
const fs = require("node:fs")
const path = require("node:path")
const root = path.join(__dirname, "..")
const manifest = JSON.parse(fs.readFileSync(path.join(root, "manifest.json"), "utf8"))
const vm = require("node:vm")
const model = {}; vm.createContext(model); vm.runInContext(fs.readFileSync(path.join(root,"Model.js"),"utf8").replace(/^\.pragma library\s*$/m,""),model)
assert.equal(manifest.id, "io.github.bolens.multi-monitor-workspaces")
assert.equal(manifest.author, "bolens")
assert.equal(manifest.version, "2.2.8")
assert.deepEqual(manifest.kinds, ["bar-widget", "service"])
assert.equal(manifest.keepLoaded, true)
assert.equal(manifest.entryPoints.barWidget, "BarWidget.qml")
assert.equal(manifest.entryPoints.service, "Service.qml")
for (const entry of Object.values(manifest.entryPoints)) assert.ok(fs.existsSync(path.join(root, entry)), `missing ${entry}`)
assert.equal(manifest.barWidget.defaults.count, 10)
assert.deepEqual(manifest.barWidget.defaults.monitorPriority, [])
assert.deepEqual(manifest.barWidget.defaults.monitorBanks, {})
assert.deepEqual(manifest.barWidget.defaults.workspaceGlyphs, {})
assert.ok(manifest.barWidget.schema.some(entry => entry.key === "workspaceGlyphs" && entry.type === "object"))
assert.ok(manifest.barWidget.schema.find(entry => entry.key === "labelMode").options.includes("hybrid"))
assert.equal(manifest.barWidget.schema.find(entry => entry.key === "buttonWidth").min, 24)
for (const key of ["activeOpacity", "occupiedOpacity", "emptyOpacity"])
  assert.equal(manifest.barWidget.schema.find(entry => entry.key === key).min, 0.45)
assert.ok(manifest.barWidget.schema.length >= 9)
for (const key of model.SETTING_KEYS) assert.deepEqual(JSON.parse(JSON.stringify(manifest.barWidget.defaults[key])), JSON.parse(JSON.stringify(model.DEFAULTS[key])), `manifest/model default drift: ${key}`)
console.log("Multi-monitor workspace manifest tests passed")
