const assert=require("node:assert/strict")
const fs=require("node:fs")
const manifest=JSON.parse(fs.readFileSync("manifest.json","utf8"))
const changelog=fs.readFileSync("CHANGELOG.md","utf8")
const license=fs.readFileSync("LICENSE","utf8")
const notice=fs.readFileSync("NOTICE","utf8")
const release=fs.readFileSync(".github/workflows/release.yml","utf8")
const readme=fs.readFileSync("README.md","utf8")
const example=fs.readFileSync("examples/dual-monitor-workspaces.lua","utf8")
assert.equal(manifest.id,"io.github.bolens.multi-monitor-workspaces")
assert.match(manifest.version,/^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)$/)
assert.match(changelog,new RegExp(`^## \\[${manifest.version.replace(/\./g,"\\.")}\\] - \\d{4}-\\d{2}-\\d{2}$`,"m"))
for(const holder of ["37signals LLC","Lukas Innig","bolens"]) assert.ok(license.includes(holder),`missing license holder: ${holder}`)
assert.ok(notice.includes("https://github.com/derluke/omarchy-dual-monitor-workspaces"))
assert.ok(release.includes('archive="omarchy-multi-monitor-workspaces-$version.tar.gz"'))
assert.match(readme,/^## Remove$/m)
assert.match(readme,/^## Requirements and dependencies$/m)
assert.match(example,/checkout --detach [a-f0-9]{40}/)
assert.doesNotMatch(example,/git clone --branch/)
const preview=fs.readFileSync("preview.png"); assert.equal(preview.subarray(1,4).toString(),"PNG")
console.log("Multi-Monitor Workspaces release and license metadata passed")
