const assert=require("node:assert/strict"),fs=require("node:fs")
assert.ok(fs.statSync("scripts/build-site.sh").mode&0o100,"site builder must remain executable")
const html=fs.readFileSync("docs/index.html","utf8"),css=fs.readFileSync("docs/styles.css","utf8")
for(const id of ["main","model","features","settings","install"]) assert.ok(html.includes(`id="${id}"`),`missing section ${id}`)
for(const asset of ["styles.css","site.js","favicon.svg","preview.png"]) assert.ok(html.includes(asset),`missing asset ${asset}`)
for(const term of ["1 → 100 monitors","Atomic topology","per-workspace glyph","Race-safe persistence"]) assert.match(html,new RegExp(term,"i"))
assert.match(html,/\{\{VERSION\}\}/); assert.match(html,/class="skip"/); assert.match(css,/prefers-reduced-motion/)
assert.match(css,/#55e6dd/i); assert.match(css,/#ff775f/i)
const image=fs.readFileSync("preview.png"); assert.equal(image.subarray(1,4).toString(),"PNG")
assert.equal((html.match(/<h1/g)||[]).length,1); assert.equal((html.match(/data-copy/g)||[]).length,1)
console.log("Multi-Monitor Workspaces Pages structure passed")
